name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls -laR chaosterraform/

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install ./

      - name: Run tests
        run: python -m pytest -v
