name: Release
on:
  push:
    tags: [ '*' ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls -laR chaosterraform/

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install ./

      - name: Run tests
        run: python -m pytest -v

      - name: Bump version
        run: |
          bumpversion --current-version '0.0.0' --new-version '${{ github.ref_name }}' patch

      - name: Run build
        run: python -m build

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        run: |
          python -m twine upload dist/*
